[[task]]
type = "short input"
give = "big"
accept = ["suli"]
reject = []

[[task]]
type = "short input"
give = "small"
accept = ["lili"]
reject = []

[[task]]
type = "short input"
give = "big animal"
accept = ["soweli suli"]
reject = []

[[task]]
type = "short input"
give = "small bird"
accept = ["waso lili"]
reject = []

[[task]]
type = "short input"
give = "The big animal sees the bird."
accept = ["soweli suli li lukin e waso."]
reject = []

[[task]]
type = "short input"
give = "The bird sees a small animal."
accept = ["waso li lukin e soweli lili."]
reject = []

[[task]]
type = "short input"
give = "bug"
accept = ["pipi"]
reject = []

[[task]]
type = "short input"
give = "The bird eats the bug."
accept = ["waso li moku e pipi."]
reject = []

[[task]]
type = "short input"
give = "The small bug sees the big animal."
accept = ["pipi lili li lukin e soweli suli."]
reject = []
