title = "This is..."

[[tasks]]
type = "short input"
give = "this"
accept = ["ni"]
reject = []

[[tasks]]
type = "short input"
give = "This is a plant."
accept = ["ni li kasi."]
reject = []

[[tasks]]
type = "short input"
give = "This plant is big."
accept = ["kasi ni li suli."]
reject = []

[[tasks]]
type = "short input"
give = "This bird eats the bug."
accept = ["waso ni li moku e pipi."]
reject = []

[[tasks]]
type = "short input"
give = "This bug is small."
accept = ["pipi ni li lili."]
reject = []

[[tasks]]
type = "short input"
give = "strong"
accept = ["wawa"]
reject = []

[[tasks]]
type = "short input"
give = "This animal is strong."
accept = ["soweli ni li wawa."]
reject = []

[[tasks]]
type = "short input"
give = "The bird looks at the strong animal."
accept = ["waso li lukin e soweli wawa."]
reject = []
