title = "Chaos!"

[[tasks]]
type = "short input"
give = "These are eyes."
accept = ["ni li lukin."]
reject = []

[[tasks]]
type = "short input"
give = "Bird eyes are strong."
accept = ["lukin waso li wawa."]
reject = []

[[tasks]]
type = "short input"
give = "Food is important."
accept = ["moku li suli."]
reject = []

[[tasks]]
type = "short input"
give = "The animal's strength is great."
accept = ["wawa soweli li suli."]
reject = []

[[tasks]]
type = "short input"
give = "Food strengthens the small animal."
accept = ["moku li wawa e soweli lili."]
reject = []

[[tasks]]
type = "short input"
give = "The food enlarges the bug."
accept = ["moku li suli e pipi."]
reject = []

[[tasks]]
type = "short input"
give = "The powerful animal turns a plant into a bird."
accept = ["soweli wawa li waso e kasi."]
reject = []
