title = "You and I"

[[tasks]]
type = "short input"
give = "The bird is strong."
accept = ["waso li wawa."]
reject = []

[[tasks]]
type = "short input"
give = "I am strong."
accept = ["mi wawa."]
reject = []

[[tasks]]
type = "short input"
give = "This animal sees food."
accept = ["soweli li lukin e moku."]
reject = []

[[tasks]]
type = "short input"
give = "You see food."
accept = ["sina lukin e moku."]
reject = []

[[tasks]]
type = "short input"
give = "The bug knows the big plant."
accept = ["pipi li sona e kasi suli."]
reject = []

[[tasks]]
type = "short input"
give = "I know the big plant."
accept = ["mi sona e kasi suli."]
reject = []

[[tasks]]
type = "short input"
give = "The bird knows the plant's size."
accept = ["waso li sona e suli kasi."]
reject = []

[[tasks]]
type = "short input"
give = "You know the plant's size."
accept = ["sina sona e suli kasi."]
reject = []
