title = "Indirect objects"

[[tasks]]
type = "short input"
give = "to"
accept = ["tawa"]
reject = []

[[tasks]]
type = "short input"
give = "You are important to me."
accept = ["sina suli tawa mi."]
reject = []

[[tasks]]
type = "short input"
give = "I like plants."
accept = ["kasi li pona tawa mi."]
reject = []

[[tasks]]
type = "short input"
give = "Food is important to people."
accept = ["moku li suli tawa jan."]
reject = []

[[tasks]]
type = "short input"
give = "Nina likes bugs."
accept = ["pipi li pona tawa jan Nina."]
reject = []

[[tasks]]
type = "short input"
give = "Ali talks to Anna."
accept = ["jan Ali li toki tawa jan Ana."]
reject = []

[[tasks]]
type = "short input"
give = "Millie talks to Nina about bugs."
accept = ["jan Mili li toki e pipi tawa jan Nina."]
reject = []
